name : advent_of_code
description : Puzzle solving of Advent of Code 2024 (visit https://adventofcode.com/2024)
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies: 
  collection: ^1.19.1

dev_dependencies:
  test: ^1.20.0

